app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from flask_login import LoginManager, UserMixin
from uuid import uuid4
from werkzeug.security import generate_password_hash

db = SQLAlchemy()

login = LoginManager()

@login.user_loader
def load_user(userid):
    return User.query.get(userid)

class User(db.Model, UserMixin):
    id = db.Column(db.String(50), primary_key=True)
    username = db.Column(db.String(100), nullable=False, unique=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    created = db.Column(db.DateTime, default=datetime.utcnow())
    api_token = db.Column(db.String(100))
   
    def __init__(self, username, email, password, first_name='', last_name= ''):
        self.username = username
        self.email = email.lower()
        self.first_name = first_name.title()
        self.last_name = last_name.title()
        self.id = str(uuid4())
        self.password = generate_password_hash(password)


class Surveys(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    stress = db.Column(db.Integer, nullable=False)
    sleep = db.Column(db.Integer, nullable=False)
    diet = db.Column(db.Integer, nullable=False)
    exercise = db.Column(db.Integer, nullable=False)
    outdoors = db.Column(db.Integer, nullable=False)
    social = db.Column(db.Integer, nullable=False)
    spirit = db.Column(db.Integer, nullable=False)

    def __init__(self, stress, sleep, diet, exercise, outdoors, social, spirit):
        self.stress = stress
        self.sleep = sleep
        self.diet = diet
        self.exercise = exercise
        self.outdoors = outdoors
        self.social = social
        self.spirit = spirit

app/__init__.py
from flask import Flask
from config import Config
from .auth.routes import auth
from .survey.routes import surveyed
from .models import db, login
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap



app = Flask(__name__)
app.config.from_object(Config)
app.register_blueprint(auth)
app.register_blueprint(surveyed)



db.init_app(app)
migrate = Migrate(app, db)
Bootstrap(app)
login.init_app(app)
login.login_view = 'auth.login'
login.login_message = 'Please log in to view this page.'
login.login_message_category = 'danger'




from . import routes

app/routes.py
from app import app
from flask import render_template, Blueprint, request, redirect, url_for, flash
import requests as r
from flask_login import login_required, current_user
from .templates.services import getQuote, ParkForm, graph_db
from googlesearch import search


@app.route('/')
def home():
    context = getQuote()
    return render_template('index.html', **context)


@app.route('/about', methods=['GET', 'POST'])
def about():
    pform = ParkForm()
    if request.method == 'POST':
        if pform.validate_on_submit():
            local = ('public parks near ' + pform.location.data)
            for p in search(local, tld="co.in", num=5, stop=5, pause=2):
                print(p)
        flash('Sorry, there was an issue with the search.')
        return render_template('about.html', form=pform, parks=p)
    return render_template('about.html', form=pform)

@app.route('/results', methods=['GET', 'POST'])
@login_required
def results():
    #context = graph_db()
    return render_template('results.html')#, **context)

   

app/survey/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, Flask
from .surveyform import ScForm
from app.models import Surveys, db
from flask_login import login_required, current_user



surveyed = Blueprint('survey', __name__, template_folder='srv_templates', url_prefix='/survey', static_folder='srv_static')

@surveyed.route('/survey', methods=['GET', 'POST'])
@login_required
def survey():
    sform = ScForm()
    if sform.validate_on_submit():
        stress = request.form['stress']
        sleep = request.form['sleep']
        diet = request.form['diet']
        exercise = request.form['exercise']
        outdoors = request.form['outdoors']
        social = request.form['social']
        spirit = request.form['spirit']

        record = Surveys(stress, sleep, diet, exercise, outdoors, social, spirit)
        db.session.add(record)
        db.session.commit()

        message = "Thank you! Your input has been submitted."
        return render_template('survey.html', message=message)
    
    else:
        for field, errors in sform.errors.items():
            for error in errors:
                flash("Error in {}: {}".format(
                    getattr(sform, field).label.text,
                    error
                ), 'error')
        return render_template('survey.html', sform=sform)

app/templates/about.html
{% extends 'components/layout.html' %}

{% block content %}
<div class="container" id="infog">
    <div class="row justify-content-center">
        <div class="col-7">
            <div style="position: relative; width: 100%; height: 0; padding-top: 80.0000%;
 padding-bottom: 48px; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAFEZye2324&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>

        </div>
    </div>
</div>

<div class="container">
  <div class="row justify-content-center" id="scfacts">
    <h5><strong>The following self-care practices have been well-researched and linked to a longer life:</strong><br></h5>
      <br>
      <br>
      <h6><strong>Exercise: </strong> People who exercised between two and eight hours per week throughout their lives reduced their risk of dying by 29 to 36 percent, according to a March 2019 study published in JAMA Network Open.<br>
      <br>
      <strong>Diet: </strong> Eating a diet filled with five servings of fruits and vegetables per day was associated with a lower risk of mortality, especially from heart-related issues, according to a July 2014 study published in The BMJ.<br>
      <br>
      <strong>Sleep: </strong> A study published in September 2017 in the Journal of the American Heart Association found too-little sleep (less than seven hours per night) was linked with higher mortality rates, though too-much sleep wasn't healthy either.<br>
      <br>
      <strong>Getting Outside: </strong> According to a 2019 study published in Lancet Planet Health, spending time in green space is associated with a lower mortality rate.<br>
    </h6>
  </div>
</div>

<div class="container" id="park">
  <div class="row justify-content-center">
      <form class="p-3" method="POST">
          {{ form.hidden_tag() }}
          <div class="form-group">
              <h3>Need to find some green space?<br>
                   Search nearby parks:</h3>
              <fieldset id="username-field">
                  {{ form.location.label }}
                  {{ form.location(class='form-control', placeholder='City, State...') }}
              </fieldset>     
          </div>
          {{ form.submit(class='btn btn-block btn-info') }}
      </form>
  </div>

  <div class="row justify-content-center">
      <h5>Submit your search, then click <a href="{{ parks }}" target="_blank">HERE</a> for your park result!</h5>
  </div>
</div>

{% endblock content %}

app/templates/components/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Self-Care Survey</title>
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Proza+Libre&display=swap" rel="stylesheet">

   <!--my css-->
    <link rel="stylesheet" href="static/css/styles.css">

</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">Self-Caring</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ url_for('home')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('about') }}">About</a>
                </li>
                </ul>
                <span class="navbar-auth">
                    <ul class="navbar-nav ml-auto">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <p>{{ "{}".format(current_user.first_name) }}</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('survey.survey') }}">Take the Survey</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('results') }}">Care Results</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        {% endif %}
                      </ul>
                </span>
            </div>
            </div>
        </nav>
    </div>
    {% block header %}
    {% endblock header %}

    {% block content %}
    <main>
       
    </main>
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends 'components/layout.html' %}


{% block content %}
<div class="container" id="whatis">
    <div class="row justify-content-center">
        <div class="col-8" id="ready">
            <h1>Ready to make yourself a priority?</h1>
            <br>
            <h3>That's what self-care is all about.</h3>
            <br>
        <img src="../static/images/yogaAM1.jpeg" alt="yoga in the morning" id="yoga1">
        </div>
        <div class="col-4" id="whats">
            <h4>What is Self-Care?</h4>
            <br>
            <p>Self-Care, in essence, is anything you do for yourself that feels nourishing. It is how we contribute to our health and wellness.</p>
            <p>Click <a href="{{ url_for('about')}}">here</a> to learn more!</p>
            <br>
            <h4>Registered Users:</h4>
            <br>
            <p>Can participate in our self-care survey.</p>
            <p>View collected data from participants.</p>
            <p>Check out suggestions for good self-care practices.</p>
            <br>
            <h5>Sign In or Register to get started!</h5>
            <center><a href="{{ url_for('auth.login') }}" class="btn btn-primary btn-sm" id="signinbtn" role="button" aria-disabled="true">Sign In</a>
            <a href="{{ url_for('auth.register') }}" class="btn btn-secondary btn-sm"  id="regbtn" role="button" aria-disabled="true">Register</a></center>
        </div>
    </div>
    <br>
</div>

{% endblock content%}

{% block footer %}
<div class="container-fluid" id="foot">
    <div class="row justify-content-center">
        <h4><i>{{ daily_quote }}</i><br> - {{ credit }}</h4>
    </div>
    <p>Inspirational quotes provided by <a href="https://zenquotes.io/" target="_blank">ZenQuotes API</a></p>
</div>
{% endblock footer %}

app/templates/results.html
{% extends 'components/layout.html' %}

{% block content %}
   <div class="container">
        <div class="row justify-content-center">
            {{ graph }}
        </div>
   </div> 

   <br>

   <div class="container">
        <div class="row justify-content-center">
            <p>How to Start a Self-Care Routine
                To get started with a self-care routine, the experts we spoke with suggest:<br>
                <ul>
                    <li>Determine which activities bring you joy, replenish your energy, and restore your balance.</li>
                    <li>Start small by choosing one behavior you'd like to incorporate into your routine in the next week.</li>
                    <li>Build up to practicing that behavior every day for one week.</li>
                    <li>Reflect on how you feel.</li>
                    <li>Add in additional practices when ready.</li>
                    <li>Get support through sharing practices from loved ones, a coach, a licensed professional (like a therapist or dietitian), or through your healthcare plan, community, or workplace.</li>
                </ul>
                <br>
                Practicing self-care doesn't need to be a heavy lift right out of the gate. Here are a few ideas to ease you into your self-care journey:<br>
                <ul>
                    <li>Journal.</li>
                    <li>Start each day by paying attention to your breath for five minutes and setting intentions for the day.</li>
                    <li>Eat breakfast.</li>
                    <li>Reflect on what you're grateful for each night.</li>
                    <li>Put your phone on airplane mode for a half hour each night and release yourself from the flurry of notifications.</li>
                    <li>Call a friend just to say hello.</li>
                    <li>Take up a relaxing hobby.</li>
                    <li>Pick a bedtime and stick to it.</li>
                </ul>
                <br>
                A review published in 2018 in the journal Health & Place analyzed data from existing studies and found that spending time outdoors can immediately lower stress levels, and that outdoor walks in green spaces are particularly effective.</p>
        </div>
   </div>


{% endblock content %}